### ISSUE TITLE
hyperscan + dpdk performance

### ISSUE THREAD

**Issue by victordetoni** [vipinpv85/DPDK-HYPERSCAN-SAMPLE#1]
Hello,

Congrats for useful code. Do you know how many pps your code can reach? I'm using E5-2420 v2 and I just can achieve ~5mpps.

**Comment by vipinpv85** [comment]
hi Victor,

I had wrote sample application on top of XEOn 4 core 4 threads model. There are a lot of things which can be optimized, like
1) per core-thread hyperscan packet process
2) work distributor model
3) Event-dev (17.05) driven worker core (hyperscan)

Please do let me know your use case and choice. I will try to suggest and share.

**Comment by vipinpv85** [comment]
Were you able to increase Mpps by distributing and optimizing the run to completion logic. Do you require help?

**Comment by vipinpv85** [comment]
Closing this issue, as this has been query. Shared suggestions and improvement ideas. Requested for updates too.

**Comment by victordetoni** [comment]
Thank you for your explanations. Actually, re-code my l3fwd sample with your hyperscan example and it worked fine. I need to adjust the code to perform with 2 or more core
