### ISSUE TITLE
  can you please explain what is being done in this project and also commands to run this with sample example?

### ISSUE THREAD

**Issue by paulworks123** [vipinpv85/DPDK-HYPERSCAN-SAMPLE#3]

**Comment by vipinpv85** [comment]
what is being done in this project 
Answer> make use of hyper scan to explore the possibility of comparing bytes for the desired string. In this project, it compares the IPv4 for the ingress frames.

also commands to run this with sample example
Answer> ./application_name <desired ipv4>
